spring:
  application:
    name: Only Notes

  main:
    allow-circular-references: true

      #-------------------------------------------------- Database

  data:
    mongodb:
      uri: {Database connection string}
      database: onlyDB
      auto-index-creation: true

jwt:
  secretKey: {secret key of jwt}